### ISSUE TITLE
Sometimes, only 2 participants are mentioned in a summary

### ISSUE THREAD

**Issue by nourou4them** [bitcoinsearch/summarizer#46]
Context: Sometimes, only 2 participants are mentioned in a summary

Solution: To group all participants or to mention them all.

![image](https://github.com/bitcoinsearch/tldr/assets/43266768/cc7a961b-75ac-4aeb-aa4f-2216b7f3a0da)

**Comment by Extheoisah** [comment]
This is beyond the scope of the frontend. This issue should be moved to the [mailing-list-summaries backend](https://github.com/bitcoinsearch/mailing-list-summaries/issues)

**Comment by urvishp80** [comment]
Can you please elaborate the issue. Are you asking to add participants in "Involving" section? or in Summary Text that we are generating above?

**Comment by Extheoisah** [comment]
I think @nourou4them is proposing grouping all the participants together when making reference to the authors of the conversation. For example, in the screenshot attached, only `Peter Todd` and `Antoine Richard` is mentioned instead of `Peter Todd, Antoine Richards and three others ....` or `Peter Todd et al., ....`
In my opinion, I don't think the current implementation is an issue but if improvements could be made and it isn't too much effort then I'm fine with it.

**Comment by urvishp80** [comment]
Thank you for an elaboration @Extheoisah. I've pushed the changes in the main branch for the same. @nourou4them
